-- AlterEnum
ALTER TYPE "FieldCategory" ADD VALUE 'FIRST_NAME';
ALTER TYPE "FieldCategory" ADD VALUE 'LAST_NAME';
ALTER TYPE "FieldCategory" ADD VALUE 'DEPARTMENT';
ALTER TYPE "FieldCategory" ADD VALUE 'JOB_TITLE';
ALTER TYPE "FieldCategory" ADD VALUE 'DEPARTMENT_JOB_TITLE';
ALTER TYPE "FieldCategory" ADD VALUE 'INDUSTRY';
