// isActiveは持たない——「今どのプロジェクトを選んでいるか」は共有相手ごとに違うため、
// Profileではなく割り当て(ProfileMember)側の状態。ProfileSummaryが閲覧者視点で解決する。
export interface Profile {
  id: string;
  ownerId: string;
  name: string;
  companyName: string;
  companyNameKana: string;
  lastName: string;
  firstName: string;
  fullName: string;
  lastNameKana: string;
  firstNameKana: string;
  furigana: string;
  department: string;
  jobTitle: string;
  industry: string;
  employeeCount: string;
  email: string;
  phone1: string;
  phone2: string;
  phone3: string;
  postalCode: string;
  address: string;
  websiteUrl: string;
  inquiryType: string;
  inquiryBody: string;
  consentPolicy: boolean;
  createdAt: Date;
  updatedAt: Date;
}
